version: '3.8'

services:
  vite:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # prevents host node_modules from messing with container
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
